<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Document</title>
</head>
<body>
	
	<script type="text/javascript">
		// ######### Try catch #########

		// if try catch gets any error only then the catch block will be invoked

		try{
			addlert('Hello')
		} catch(err){
			console.log( err)
		}
		finally{
			console.log("Heyy I will be called all the timee")
		}

		// try ---> is a block is some codes that you wanna try to catch the error
		// catch ---> receives an error as an object which has name and message property
		// finally ---> is such a block which will obviously be executed

		// let error = {}
		try{
			let x = 6

			if (x >= 12) throw {
				name: 'Bigger Problem',
				message : 'x is Bigger'
			};
			if (x < 12) throw {
				name: 'Smaller Problem',
				message : 'x is smaller'
			};
		} catch(error){
			console.log(error)
		}


		// ========= Types of error ==============

			// --- range error ---- is thrown if you use a number that is outside the range of legal values.
			try{
				45534.335443.toFixed(500)
			}
			catch(err){
				console.log(err.message)
			}



			// --- syntax error ---- A SyntaxError is thrown if you try to evaluate code with a syntax error
			try{
				eval("alert('Hello)");

			}
			catch(err){
				console.log(err.message)
			}




			// --- reference error ---- is thrown if you use (reference) a variable that has not been declared

			let x = 5;
			try {
			  x = y + 1;   // y cannot be used (referenced)
			}
			catch(err) {
			  console.log(err.name)
			}



			// type error --- is thrown when I use any type related miss statetement

			let num = 1;
			try {
			  num.toUpperCase();   // You cannot convert a number to upper case
			}
			catch(err) {
			  console.log(err.name)
			}

			// console.log('hallo')
	</script>
</body>
</html>